name: CI

on:
  push:
    branches: ['develop']
  workflow_dispatch:
jobs:
  eslint:
    runs-on: ubuntu-latest
    runs:
      using: 'node16'
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Install dependencies
        run: npm ci

      - name: Run ESLint
        run: npm run lint
